Repository operator-framework/api, pull requests merged in 2020-05, with the labels that each got.

#31 Update OLM to use UID for OG Labels
  pkg/operators/v1/operatorgroup_types.go
Labels: approved

#32 validation: bundle CRDs are compared by definition key instead of name
  pkg/validation/internal/bundle.go
  pkg/validation/internal/bundle_test.go
  pkg/validation/internal/csv.go
Labels: kind/bug, lgtm

#33 Remove Bundle validator from the validator list
  pkg/validation/internal/bundle.go
  pkg/validation/internal/bundle_test.go
  pkg/validation/validation.go
Labels: lgtm

#34 Update webhook description
  crds/operators.coreos.com_clusterserviceversions.yaml
  crds/zz_defs.go
  pkg/operators/v1alpha1/clusterserviceversion_types.go
Labels: lgtm

#36 WebhookDesc should use containerPort field
  pkg/operators/v1alpha1/clusterserviceversion_test.go
  pkg/operators/v1alpha1/clusterserviceversion_types.go
Labels: lgtm

#37 pkg/manifests: use yaml decoder to avoid conversion errors
  pkg/manifests/bundleloader.go
  pkg/manifests/packagemanifestloader.go
Labels: kind/bug, lgtm

#38 pkg/manifests: `loadBundle` returns an error if a subdir or hidden file is found
  pkg/manifests/bundleloader.go
  pkg/manifests/directory_test.go
  pkg/manifests/testdata/invalid_bundle_with_hidden/.hidden
  pkg/manifests/testdata/invalid_bundle_with_hidden/test-operator.clusterserviceversion.yaml
  pkg/manifests/testdata/invalid_bundle_with_hidden/test.example.com_tests_crd.yaml
  pkg/manifests/testdata/invalid_bundle_with_subdir/foo/.keep
  pkg/manifests/testdata/invalid_bundle_with_subdir/test-operator.clusterserviceversion.yaml
  pkg/manifests/testdata/invalid_bundle_with_subdir/test.example.com_tests_crd.yaml
Labels: lgtm
