Repository operator-framework/api, pull requests merged in 2022-01, with the labels that each got.

#206 validator/good practices: Improve message
  pkg/validation/internal/good_practices.go
  pkg/validation/internal/good_practices_test.go
Labels: lgtm, approved

#207 csv_validator: add check to ensure that the example is a valid JSON
  pkg/validation/internal/csv.go
  pkg/validation/internal/csv_test.go
  pkg/validation/internal/testdata/invalid.alm-examples.csv.yaml
Labels: lgtm, approved

#211 fix(constraint): Correct the message field to be failureMessage
  pkg/constraints/constraint.go
  pkg/constraints/constraint_test.go
Labels: lgtm, approved

#215 fix: alm-example parse check should not fail when the annotation if empty
  pkg/validation/internal/csv.go
  pkg/validation/internal/csv_test.go
  pkg/validation/internal/testdata/correct.csv.empty.example.yaml
Labels: lgtm, approved

#209 Added field for optional manifests
  crds/operators.coreos.com_installplans.yaml
  crds/zz_defs.go
  pkg/operators/v1alpha1/installplan_types.go
Labels: ok-to-test, lgtm, approved

#216 Remove estroz from OWNERS
  OWNERS
Labels: lgtm, approved

#218 Add awgreene to list of approvers in OWNERS file
  OWNERS
Labels: lgtm, approved

#169 (catsrc) add custom unmarshaller for registry poll interval
  pkg/operators/v1alpha1/catalogsource_types.go
  pkg/operators/v1alpha1/types_test.go
Labels: lgtm, approved

#219 Add perdasilva to approvers
  OWNERS
Labels: lgtm, approved

#208 deprecate-api validator: add checks for removed APIs on 1.25 and 1.26
  README.md
  pkg/validation/internal/operatorhub.go
  pkg/validation/internal/removed_apis.go
  pkg/validation/internal/removed_apis_test.go
  pkg/validation/internal/testdata/removed_api_1_25/cache.example.com_memcacheds.yaml
  pkg/validation/internal/testdata/removed_api_1_25/horizontal-pod.yaml
  pkg/validation/internal/testdata/removed_api_1_25/memcached-operator.clusterserviceversion.yaml
  pkg/validation/internal/testdata/removed_api_1_25/policy.yaml
  pkg/validation/internal/testdata/removed_api_1_26/cache.example.com_memcacheds.yaml
  pkg/validation/internal/testdata/removed_api_1_26/horizontal-pod.yaml
  pkg/validation/internal/testdata/removed_api_1_26/memcached-operator.clusterserviceversion.yaml
  pkg/validation/validation.go
Labels: lgtm, approved

#214 .github/workflows: Add workflow_dispatch event trigger
  .github/workflows/go.yaml
  .github/workflows/verify.yml
Labels: lgtm, approved

#217 feat: add warning for olm.properties being defined when validating csv
  pkg/validation/errors/error.go
  pkg/validation/internal/annotations.go
  pkg/validation/internal/community.go
  pkg/validation/internal/csv_test.go
  pkg/validation/internal/testdata/correct.csv.olm.properties.annotation.yaml
Labels: lgtm, approved

#221 refactor(constraint): update none compound constraint to be not
  pkg/constraints/constraint.go
  pkg/constraints/constraint_test.go
Labels: lgtm, approved

#224 .github/workflows: Update the pull_request trigger for the Go workflow
  .github/workflows/go.yaml
Labels: lgtm
